version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: userdb
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      discovery.type: single-node
    ports:
      - '9200:9200'

  user-service:
    build:
      context: .
      dockerfile: cmd/user-service/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      DATABASE_DSN: ${USER_SERVISE_DATABASE_DSN}

volumes:
  pg_data:
  minio_data:
